--PRAGMA JOURNAL_MODE=wal;
CREATE TABLE IF NOT EXISTS plant (
    name        TEXT,       -- Name of the plant
    final_stage INTEGER,    -- The final growth stage when it can be harvested
    CONSTRAINT plant_pk_name PRIMARY KEY (name)
);
CREATE TABLE IF NOT EXISTS sfx (
    name    TEXT,       -- Name of the sfx resource
    CONSTRAINT sfx_pk_name PRIMARY KEY (name)
);
CREATE TABLE IF NOT EXISTS tile (
    name    TEXT,        -- Name of the tile
    CONSTRAINT tile_pk_name PRIMARY KEY (name)
);
CREATE TABLE IF NOT EXISTS animal (
    name        TEXT,       -- Name of the animal
    dangerous   BOOLEAN,    -- Whether or not it will aggro you
    CONSTRAINT animal_pk_name PRIMARY KEY (name)
);
-- plant
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/flax', 3);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/barley', 3);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/carrot', 3);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/poppy', 4);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/hemp', 3);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/pipeweed', 4);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/beet', 3);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/hops', 6);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/peas', 4);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/yellowonion', 3);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/pumpkin', 4);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/pepper', 6);
INSERT OR IGNORE INTO plant VALUES ('gfx/terobjs/plants/wine', 6);
-- tiles
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/beach');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/beechgrove');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/bluesod');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/boards');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/bog');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/bogwater');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/cave');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/cloudrange');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/deep');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/dirt');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/dryflat');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/fen');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/fenwater');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/field');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/flowermeadow');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/grass');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/greensward');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/hardsteppe');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/heath');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/highground');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/leaf');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/leafpatch');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/lichenwold');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/lushfield');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/mine');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/moor');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/mossbrush');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/mountain');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/nil');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/oakwilds');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/acrebrick');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/argentite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/ballbrick');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/basalt');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/blackcoal');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/cassiterite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/catgold');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/chalcopyrite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/cinnabar');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/dolomite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/feldspar');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/flint');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/galena');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/gneiss');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/granite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/hematite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/ilmenite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/limestone');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/limonite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/magnetite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/malachite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/marble');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/nagyagite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/petzite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/porphyry');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/quartz');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/sandstone');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/schist');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/slag');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/paving/sylvanite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/pinebarren');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/redplain');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/ridges/cavein');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/ridges/caveout');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/ridges/soil');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/argentite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/basalt');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/blackcoal');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/cassiterite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/chalcopyrite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/cinnabar');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/dolomite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/feldspar');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/flint');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/galena');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/gneiss');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/granite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/hematite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/ilmenite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/limestone');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/limonite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/magnetite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/malachite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/marble');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/petzite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/porphyry');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/quartz');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/sandstone');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/schist');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rocks/sylvanite');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/rootbosk');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/sandcliff');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/seabed');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/shadycopse');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/skycube');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/snow');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/sombrebramble');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/spave');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/swamp');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/swampwater');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/timberland');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/wald');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/water');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/wildturf');
INSERT OR IGNORE INTO tile VALUES ('gfx/tiles/wn');
-- sfx files
INSERT OR IGNORE INTO sfx VALUES ('sfx/blowing');
INSERT OR IGNORE INTO sfx VALUES ('sfx/bone');
INSERT OR IGNORE INTO sfx VALUES ('sfx/breakwood');
INSERT OR IGNORE INTO sfx VALUES ('sfx/balders');
INSERT OR IGNORE INTO sfx VALUES ('sfx/build');
INSERT OR IGNORE INTO sfx VALUES ('sfx/chip');
INSERT OR IGNORE INTO sfx VALUES ('sfx/choppan');
INSERT OR IGNORE INTO sfx VALUES ('sfx/clank');
INSERT OR IGNORE INTO sfx VALUES ('sfx/clonk');
INSERT OR IGNORE INTO sfx VALUES ('sfx/creak2');
INSERT OR IGNORE INTO sfx VALUES ('sfx/creakdoor');
INSERT OR IGNORE INTO sfx VALUES ('sfx/drinkan');
INSERT OR IGNORE INTO sfx VALUES ('sfx/exp');
INSERT OR IGNORE INTO sfx VALUES ('sfx/heavydoor');
INSERT OR IGNORE INTO sfx VALUES ('sfx/lvlup');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fanfar');
INSERT OR IGNORE INTO sfx VALUES ('sfx/farman');
INSERT OR IGNORE INTO sfx VALUES ('sfx/hammer');
INSERT OR IGNORE INTO sfx VALUES ('sfx/heathbird');
INSERT OR IGNORE INTO sfx VALUES ('sfx/jump');
INSERT OR IGNORE INTO sfx VALUES ('sfx/land');
INSERT OR IGNORE INTO sfx VALUES ('sfx/squeak');
INSERT OR IGNORE INTO sfx VALUES ('sfx/swoosh');
INSERT OR IGNORE INTO sfx VALUES ('sfx/match');
INSERT OR IGNORE INTO sfx VALUES ('sfx/meat');
INSERT OR IGNORE INTO sfx VALUES ('sfx/metalhinge');
INSERT OR IGNORE INTO sfx VALUES ('sfx/metalhit');
INSERT OR IGNORE INTO sfx VALUES ('sfx/mineout');
INSERT OR IGNORE INTO sfx VALUES ('sfx/plop');
INSERT OR IGNORE INTO sfx VALUES ('sfx/plums');
INSERT OR IGNORE INTO sfx VALUES ('sfx/plums-big');
INSERT OR IGNORE INTO sfx VALUES ('sfx/ropecreak');
INSERT OR IGNORE INTO sfx VALUES ('sfx/runningwater');
INSERT OR IGNORE INTO sfx VALUES ('sfx/treefall');
INSERT OR IGNORE INTO sfx VALUES ('sfx/thud');
INSERT OR IGNORE INTO sfx VALUES ('sfx/wading');
INSERT OR IGNORE INTO sfx VALUES ('sfx/twang');
INSERT OR IGNORE INTO sfx VALUES ('sfx/borka/butcher');
INSERT OR IGNORE INTO sfx VALUES ('sfx/borka/leafrustle');
INSERT OR IGNORE INTO sfx VALUES ('sfx/borka/shoveldig');
INSERT OR IGNORE INTO sfx VALUES ('sfx/borka/sowing');
INSERT OR IGNORE INTO sfx VALUES ('sfx/borka/cc-scream');
INSERT OR IGNORE INTO sfx VALUES ('sfx/borka/bitedust');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fight/antspit');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fight/armorcrash');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fight/arm-soak1');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fight/arm-soak2');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fight/you-lose');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fight/you-win');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fx/flame');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fx/metal');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fx/burnhand');
INSERT OR IGNORE INTO sfx VALUES ('sfx/fx/tar');
INSERT OR IGNORE INTO sfx VALUES ('sfx/inst/drum');
INSERT OR IGNORE INTO sfx VALUES ('sfx/inst/fiddle');
INSERT OR IGNORE INTO sfx VALUES ('sfx/inst/flute');
INSERT OR IGNORE INTO sfx VALUES ('sfx/inst/lute');
INSERT OR IGNORE INTO sfx VALUES ('sfx/items/pickaxe');
INSERT OR IGNORE INTO sfx VALUES ('sfx/items/stretch');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/items/die');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/arch/door');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/anvil');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/cauldron');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/grinder');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/plow');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/quern');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/rustygate');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/swheel');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/thud-wood');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/woodcrash');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/woodcrash2');
INSERT OR IGNORE INTO sfx VALUES ('sfx/terobjs/woodspin');
-- animals
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/badger/badger', 1);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/bear/bear', 1);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/bat/bat', 1);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/boar/boar', 1);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/mammoth/mammoth', 1);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/troll/troll', 1);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/lynx/lynx', 1);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/wolf/wolf', 1);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/fox/fox', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/rabbit/rabbit', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/reddeer/reddeer', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/dryad/dryad', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/ants/ants', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/cattle/bull', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/cattle/cattle', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/cattle/cow', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/cattle/aurochs', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/chicken/chick', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/chicken/chicken', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/chicken/hen', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/chicken/rooster', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/hedgehog/hedgehog', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/horse/horse', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/horse/mare', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/horse/stallion', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/ladybug/ladybug', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/moose/moose', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/rat/rat', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/sheep/sheep', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/sheep/ram', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/sheep/mouflon', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/silkmoth/silkmoth', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/squirrel/squirrel', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/toad/toad', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/frog/frog', 0);
INSERT OR IGNORE INTO animal VALUES('gfx/kritter/dragonfly/dragonfly', 0);